export default [
  {
    id: 'plus',
    type: 'bar',
    fill: 'green',
    title: 'Положительное влияние',
    isTitleShow: false,
    isFullHeight: true,
  },
  {
    id: 'ost',
    type: 'bar',
    fill: 'gray',
    title: 'Остаточная оценка',
    isTitleShow: false,
    isFullHeight: true,
  },
  {
    id: 'cur',
    type: 'bar',
    title: 'Текущая оценка',
    fill: 'white',
    isTitleShow: false,
    isFullHeight: true,
  },
  {
    id: 'risk',
    type: 'line',
    fill: 'red',
    title: 'Риск аппетит',
    isTitleShow: true,
    isFullHeight: false,
  },
  {
    id: 'fact',
    type: 'bar',
    fill: 'black',
    title: 'Факт',
    isTitleShow: true,
    isFullHeight: false,
  },
];
